version: '3.8'

services:
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    init: true
    image: mariadb
    container_name: mariadb
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - wordpress_db:/var/lib/mysql
    networks:
      - docker-network

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    init: true
    restart: unless-stopped
    container_name: wordpress
    depends_on:
      - mariadb
    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_NAME=${MYSQL_DATABASE}
      - WORDPRESS_DB_USER=${MYSQL_USER}
      - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - docker-network

  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    init: true
    image: nginx
    restart: unless-stopped
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - '443:443'
    volumes:
      - ./requirements/nginx/conf/cert.pem:/etc/ssl/certs/cert.pem
      - ./requirements/nginx/conf/key.pem:/etc/ssl/private/key.pem
    networks:
      - docker-network

volumes:
  wordpress_db:
  wordpress_data:

networks:
    docker-network:
        driver: bridge